- name: ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create a docker network
      docker_network:
        name: yan

    - name: Re-create a Spring container
      docker_container:
        name: ecommerce
        image: yamiannephilim/ecommerce
        networks:
          - name: yan
            aliases:
              - e-commerce
        state: started
        recreate: yes
        exposed_ports:
          - 8080
        detach: true
        published_ports:
          - 8080:8080
        pull: true
        comparisons:
          image: strict

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
