- name: ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create a docker network
      docker_network:
        name: yan

    - name: Re-create a container
      docker_container:
        name: portugal-hotel-booking
        image: yamiannephilim/dash
        networks:
          - name: yan
            aliases:
              - portugal-hotel-booking
        state: started
        recreate: yes
        exposed_ports:
          - 8050
        detach: true
        published_ports:
          - 8050:8050
        pull: true
        comparisons:
          image: strict

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
